apiVersion: v1
kind: Service
metadata:
  namespace: mongodb
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: mongodb
  name: mongo-nodeport
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: NodePort

